(defun fibonacci ()
  (print "Calculemos el término n de la serie Fibonacci, ingresa tu número n: ")
  (read)
  )

(defun opef (n)
  (if (< n 2)
      (let ((n(+ (fibonacci (- n 1)) (fibonacci (- n 2)))
              (format t "%~s es ~s en la serie Fibonacci%" fib (float rfib))
             rfib)))
  )
  )

(let ((ene (fibonacci)))
  (opef ene))