(defun fibonacci()
(print "Ingrese el valor de n para calcular su termino en la serie Fibonacci: ")
(let ((nf (read)))
(if (< nf 2)
(* nf (- 2 1))
  (+ (- nf 1) (- nf 2)))
  ))

(let ((fibores (fibonacci)))
(format t "El resultado es: ~s." fibores))